// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dszwidenccggatcyuabr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzendpZGVuY2NnZ2F0Y3l1YWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2Nzg5MjksImV4cCI6MjA5MjI1NDkyOX0.8qO9MwAkxen5mL0y_f4RzJobGJ2lsmL5pc8GaPla4GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});